### ISSUE TITLE
scale of graph has increased making it hard to see the actual data

### ISSUE THREAD

**Issue by matteius** [lincolnloop/python-package-manager-shootout#11]
Graph scale used to go up to 120 in increments of 20 but now it goes up to 600 in increments of 100 -- from what I can tell no project in any of the categories exceeds 200 seconds, and this makes the graphs less useful to look at now:

Example:
Tooling beore:
![image](https://github.com/lincolnloop/python-package-manager-shootout/assets/479892/576c7bc6-5df9-4ccc-a874-a3e29b43ed99)

Tooling now:
![image](https://github.com/lincolnloop/python-package-manager-shootout/assets/479892/3d4c1ef7-49dc-484b-906a-1b1af6bc5116)

**Comment by ipmb** [comment]
Huh... thanks for calling this out. I can't think of anything that has changed to cause this, but I'll dig into it.

**Comment by ipmb** [comment]
Ah, I see the issue.

![image](https://github.com/lincolnloop/python-package-manager-shootout/assets/319156/12c1058a-3005-460f-bf19-a8b9c2c5f3cf)

Looks like Poetry had one really slow run that threw the scales off. All the graphs are set to the same scale so the delta's are on the same scale across the board.

Assuming this was just a one-off fluke, it should fix itself within the day as that bad data gets replaced.
