### ISSUE TITLE
Current visualization with max value 

### ISSUE THREAD

**Issue by oz123** [lincolnloop/python-package-manager-shootout#12]
Hi,
The current visualization using the same y-axis for all graphs results in a way too big scale for most graphs .
This in turn makes differences seems negligent.
Will you accept a PR for changing this?

**Comment by ipmb** [comment]
There was some discussion on this in #11. Since then, it looks like Poetry's performance has degraded significantly, making this more of a permanent issue. I'd be open to a PR that scales each graph independently.
