### ISSUE TITLE
Can add rye to compare list too?

### ISSUE THREAD

**Issue by GMYXDS** [lincolnloop/python-package-manager-shootout#19]
Rye ： https://github.com/astral-sh/rye

**Comment by dimbleby** [comment]
per their [README](https://github.com/astral-sh/rye?tab=readme-ov-file#in-the-box)

> Locking and Dependency Installation: is today implemented by using [uv](https://github.com/astral-sh/uv) with a fallback to [unearth](https://pypi.org/project/unearth/) and [pip-tools](https://github.com/jazzband/pip-tools/).

ie rye is just wrapping uv for the tasks that are measured in these benchmarks.  There seems little value in measuring it separately?

**Comment by GMYXDS** [comment]
I see.
In the near future, UV will merge with RIE. 
And now rye has built-in UV as a package manager.
 So measuring rye alone doesn't really make much sense. 

I will close this issue，Thank you all！
