### ISSUE TITLE
Use project management commands in uv benchmark (e.g. `uv lock`)

### ISSUE THREAD

**Issue by Di-Is** [lincolnloop/python-package-manager-shootout#24]
In order to make a fair comparison between `pdm`,`poetry` and `uv`, it would be better to change the command used in the `uv` benchmark.

- `uv add`: add package
- `uv lock`: generate lock file
- `uv lock -U`: update lock file
- `uv sync`: install packages

**Comment by ipmb** [comment]
resolved in #25
