### ISSUE TITLE
Only show stats if there are at least 2 datapoints

### ISSUE THREAD

**Issue by ipmb** [lincolnloop/python-package-manager-shootout#7]
When new versions of the tools are picked up for testing, we shouldn't display them until there have been at least 2 runs of the benchmark against them.

There is probably some clever SQL to do this here, https://github.com/lincolnloop/python-package-manager-shootout/blob/254a968b7991852098fad849f4b1530dbdffbea4/bin/generate_average_stats.sh#L29-L40

**Comment by ipmb** [comment]
Here's a boiled down test case. Starting with [this csv](https://github.com/lincolnloop/python-package-manager-shootout/files/9184062/full.csv) and this command:

```shell
 sqlite-utils memory full.csv \ 
   "SELECT 
     printf(\"%s %s\", tool, version) AS tool, 
     stat, 
     ROUND(AVG(\"elapsed time\"), 2) AS \"elapsed time\", 
   FROM full 
   GROUP BY tool,version,stat" \ 
   --csv
```
 
It should _not_ output anything about `poetry 9.9.9` because there is only one round of results in the CSV for that tool/version/stat combination.

**Comment by wwymak** [comment]
you just need to filter by count? eg

```bash
sqlite-utils memory full.csv \ 
"SELECT *  FROM (SELECT
    printf(\"%s %s\", tool, version) AS tool, 
    stat,
    COUNT(*) AS num_entries
    ROUND(AVG(\"elapsed time\"), 2) AS \"elapsed time\"
   FROM full
    GROUP BY tool,version,stat) WHERE num_entries > 1" \
--csv
```

**Comment by ipmb** [comment]
I believe that `COUNT(*)` is counting the total number of rows where the functionality we need is to count the number of rows in each group.

**Comment by wwymak** [comment]
No, I don’t think so— if you use `COUNT(*)` with the groupby it gives the number of rows per group— it works on the same aggregation level as the `AVG` in your original query does

**Comment by ipmb** [comment]
It's not working as expected for me,

```shell
$ curl -sLO https://github.com/lincolnloop/python-package-manager-shootout/files/9184062/full.csv
$ sqlite-utils memory full.csv \
> "SELECT *  FROM (SELECT
    printf(\"%s %s\", tool, version) AS tool,
    stat,
    COUNT(*) AS num_entries,
    ROUND(AVG(\"elapsed time\"), 2) AS \"elapsed time\"
   FROM full
    GROUP BY tool,version,stat) WHERE num_entries > 1" \
--csv | grep 9.9.9
poetry 9.9.9,add-package,2,10.08
poetry 9.9.9,install-warm,2,129.99
poetry 9.9.9,update,2,94.77
```

The expected output there would be empty.

**Comment by wwymak** [comment]
But the csv file you linked has 2 entries each for each of those poetry 9.9.9 stats — shouldn’t the results be showing for them?

**Comment by ipmb** [comment]
gah! you're right... If I change to `num_entries > 2`, it _does_ do what I'd expect. Thanks @wwymak! I'll get this updated shortly.
