### ISSUE TITLE
pipenv no longer on graph?

### ISSUE THREAD

**Issue by matteius** [lincolnloop/python-package-manager-shootout#9]
Went to check the performance of the new release of `pipenv` and its not on the graph from what I can tell.

![image](https://user-images.githubusercontent.com/479892/200109275-b3832f17-d535-4dc5-9d6c-24e261d804a7.png)

**Comment by ipmb** [comment]
We were requiring at least 3 datapoints to show up on the graph. When a new version was released that meant there was a window where neither the new or old version would hit that number. I've reduced it to 2 which should resolve the issue moving forward.
